### ISSUE TITLE
Check and implement support in Firefox.

### ISSUE THREAD

**Issue by jjaone** [abacaj/chatgpt-backup#1]
Test the script in firefox browser and if doesn't work implement proper fix so that Mozilla browsers are supported.

**Comment by abacaj** [comment]
Hi, I just tried it in firefox and it worked without changing any of the code.
My version: ```Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0```

The only thing I had to do was type `allow pasting` into console before firefox will let you paste a script like this.

**Comment by jjaone** [comment]
Thanks, much appreciated 💪
